class AddStatsToShipClass < ActiveRecord::Migration
  def change
    add_column :ship_classes, :base_cost, :integer
    add_column :ship_classes, :officers, :integer
    add_column :ship_classes, :enlisted, :integer
    add_column :ship_classes, :marines, :integer
    add_column :ship_classes, :small_craft, :text
    add_column :ship_classes, :recon_drones, :integer
    add_column :ship_classes, :fore_fcon, :text
    add_column :ship_classes, :fore_mag, :integer
    add_column :ship_classes, :fore_missiles, :text
    add_column :ship_classes, :fore_energy, :text
    add_column :ship_classes, :fore_cm, :text
    add_column :ship_classes, :fore_pd, :text
    add_column :ship_classes, :fore_decoy, :integer
    add_column :ship_classes, :aft_fcon, :text
    add_column :ship_classes, :aft_mag, :integer
    add_column :ship_classes, :aft_missiles, :text
    add_column :ship_classes, :aft_energy, :text
    add_column :ship_classes, :aft_cm, :text
    add_column :ship_classes, :aft_pd, :text
    add_column :ship_classes, :aft_decoy, :integer
    add_column :ship_classes, :port_fcon, :text
    add_column :ship_classes, :port_mag, :integer
    add_column :ship_classes, :port_missiles, :text
    add_column :ship_classes, :port_energy, :text
    add_column :ship_classes, :port_cm, :text
    add_column :ship_classes, :port_pd, :text
    add_column :ship_classes, :port_decoy, :integer
    add_column :ship_classes, :star_fcon, :text
    add_column :ship_classes, :star_mag, :integer
    add_column :ship_classes, :star_missiles, :text
    add_column :ship_classes, :star_energy, :text
    add_column :ship_classes, :star_cm, :text
    add_column :ship_classes, :star_pd, :text
    add_column :ship_classes, :star_decoy, :integer
    add_column :ship_classes, :scale, :integer
    add_column :ship_classes, :core_armor, :integer
    add_column :ship_classes, :star_sidewall, :text
    add_column :ship_classes, :port_sidewall, :text
    add_column :ship_classes, :brg, :text
    add_column :ship_classes, :flg, :text
    add_column :ship_classes, :lif, :integer
    add_column :ship_classes, :com, :integer
    add_column :ship_classes, :ecm, :text
    add_column :ship_classes, :piv, :text
    add_column :ship_classes, :rol, :text
    add_column :ship_classes, :fwd, :integer
    add_column :ship_classes, :aft, :integer
    add_column :ship_classes, :thrust, :text
    add_column :ship_classes, :hyp, :integer
    add_column :ship_classes, :hull, :integer
    add_column :ship_classes, :si, :text
    add_column :ship_classes, :repair_parties, :text
    add_column :ship_classes, :range_bands, :text
    add_column :ship_classes, :cost_adjusters, :text
  end
end
